port: 8080
charts:
  - name: debug
    regex: "DEBUG - Slow response: path=.*?, user=.*?, duration=(\\d+\\.\\d+)s"
    x_axis: Index
    y_axis: DEBUG Time (s)
    color: "#ff6384"

  - name: info
    regex: "INFO - Response sent: path=.*?, user=.*?, duration=(\\d+\\.\\d+)s"
    x_axis: Index
    y_axis: INFO Time (s)
    color: "#36a2eb"

